/* ============================================================
   journal.js — قيود اليومية
   يحتوي على: فتح نافذة القيد، إضافة/حذف سطر، حساب التوازن،
   حفظ القيد، حذف القيد، عرض جدول القيود
   ============================================================ */

/* ============================================================
   نافذة القيد (Journal Modal)
   ============================================================ */
function openJournalModal(entryId = null, autoLines = null) {
  S._edit   = entryId ? 'edit' : 'new';
  S._editId = entryId;

  document.getElementById('journal-modal-title').textContent = entryId ? 'تعديل القيد' : 'قيد يومي جديد';
  document.getElementById('j-lines').innerHTML = '';
  jLineCount = 0;

  // إعادة تعيين الحقول
  const today = new Date().toISOString().split('T')[0];
  document.getElementById('j-date').value = today;
  document.getElementById('j-desc').value = '';
  document.getElementById('j-ref').value  = '';
  document.getElementById('j-balance-status').style.display = 'none';

  const autoNote = document.getElementById('j-auto-note');
  autoNote.style.display = 'none';

  if (entryId) {
    // وضع التعديل: تعبئة البيانات الموجودة
    const e = S.journalEntries.find(x => x.id === entryId);
    if (e) {
      document.getElementById('j-number').value = e.number;
      document.getElementById('j-date').value   = e.date;
      document.getElementById('j-desc').value   = e.desc;
      document.getElementById('j-ref').value    = e.ref || '';
      if (e.autoGenerated) autoNote.style.display = 'block';
      e.lines.forEach(l => addJournalLine(l));
    }
  } else {
    // وضع الإضافة: رقم تلقائي
    document.getElementById('j-number').value = 'JE-' + String(S.journalEntries.length + 1).padStart(4, '0');
    if (autoLines) {
      autoNote.style.display = 'block';
      autoLines.forEach(l => addJournalLine(l));
    } else {
      // سطران افتراضيان فارغان
      addJournalLine();
      addJournalLine();
    }
  }

  openModal('journal-modal');
}

/* ===== إضافة سطر جديد في القيد ===== */
function addJournalLine(data = null) {
  const tbody = document.getElementById('j-lines');
  const id    = 'jl-' + (++jLineCount);

  // بناء قائمة الحسابات (نعرض كل الحسابات)
  const opts = S.accounts
    .map(a => `<option value="${a.id}" ${data && data.accountId === a.id ? 'selected' : ''}>${a.code} - ${a.name}</option>`)
    .join('');

  const tr = document.createElement('tr');
  tr.id = id;
  tr.innerHTML = `
    <td><select class="jl-account" onchange="updateJBalance()">${opts}</select></td>
    <td><input type="text" class="jl-desc" value="${data ? escH(data.desc || '') : ''}" placeholder="بيان فرعي"></td>
    <td><input type="number" class="jl-debit"  value="${data && data.debit  > 0 ? data.debit  : ''}" min="0" step="0.01" oninput="clearOpposite(this,'jl-credit');updateJBalance()"></td>
    <td><input type="number" class="jl-credit" value="${data && data.credit > 0 ? data.credit : ''}" min="0" step="0.01" oninput="clearOpposite(this,'jl-debit');updateJBalance()"></td>
    <td><button class="btn btn-danger btn-sm" onclick="document.getElementById('${id}').remove();updateJBalance()">✕</button></td>`;

  tbody.appendChild(tr);
  updateJBalance();
}

/* ===== منع إدخال مدين ودائن في نفس السطر ===== */
function clearOpposite(el, oppClass) {
  if (el.value) {
    const tr  = el.closest('tr');
    const opp = tr.querySelector('.' + oppClass);
    if (opp) opp.value = '';
  }
}

/* ===== حساب ومؤشر توازن القيد ===== */
function updateJBalance() {
  let dr = 0, cr = 0;
  document.querySelectorAll('#j-lines tr').forEach(tr => {
    dr += parseFloat(tr.querySelector('.jl-debit')?.value  || 0);
    cr += parseFloat(tr.querySelector('.jl-credit')?.value || 0);
  });

  const el   = document.getElementById('j-balance-status');
  el.style.display = 'block';
  const diff = Math.abs(dr - cr);

  if (diff < 0.01) {
    el.style.cssText = 'display:block;background:var(--green-dim);color:var(--green);font-size:12px;font-weight:700;padding:7px 13px;border-radius:8px;margin-top:8px;';
    el.textContent   = `✓ متوازن — المدين: ${fmt(dr)} | الدائن: ${fmt(cr)}`;
  } else {
    el.style.cssText = 'display:block;background:var(--red-dim);color:var(--red);font-size:12px;font-weight:700;padding:7px 13px;border-radius:8px;margin-top:8px;';
    el.textContent   = `⚠ غير متوازن — المدين: ${fmt(dr)} | الدائن: ${fmt(cr)} | الفرق: ${fmt(diff)}`;
  }
}

/* ============================================================
   حفظ القيد
   ============================================================ */
function saveJournalEntry() {
  const date   = document.getElementById('j-date').value;
  const desc   = document.getElementById('j-desc').value.trim();
  const ref    = document.getElementById('j-ref').value.trim();
  const number = document.getElementById('j-number').value;

  if (!date || !desc) { showToast('يرجى ملء التاريخ والبيان', 'error'); return; }

  // جمع بنود القيد
  const lines = [];
  let dr = 0, cr = 0;
  document.querySelectorAll('#j-lines tr').forEach(tr => {
    const accountId = tr.querySelector('.jl-account')?.value;
    const ldesc     = tr.querySelector('.jl-desc')?.value || '';
    const d         = parseFloat(tr.querySelector('.jl-debit')?.value  || 0);
    const c         = parseFloat(tr.querySelector('.jl-credit')?.value || 0);
    if (accountId && (d > 0 || c > 0)) {
      lines.push({ accountId, desc: ldesc, debit: d, credit: c });
      dr += d;
      cr += c;
    }
  });

  if (lines.length === 0)          { showToast('أضف بنوداً للقيد', 'error'); return; }
  if (Math.abs(dr - cr) > 0.01)   { showToast('القيد غير متوازن! مدين ≠ دائن', 'error'); return; }

  if (S._edit === 'edit' && S._editId) {
    const idx = S.journalEntries.findIndex(e => e.id === S._editId);
    if (idx > -1)
      S.journalEntries[idx] = { ...S.journalEntries[idx], date, desc, ref, number, lines, debitTotal: dr, creditTotal: cr };
  } else {
    S.journalEntries.push({
      id: uid(), number, date, desc, ref,
      lines, debitTotal: dr, creditTotal: cr,
      status: 'مرحّل', autoGenerated: false
    });
  }

  save();
  closeModal('journal-modal');
  updateAll();
  showToast('تم حفظ القيد ✓', 'success');
}

/* ============================================================
   حذف القيد
   ============================================================ */
function deleteJournalEntry(id) {
  if (!confirm('حذف هذا القيد؟')) return;

  // التحقق من ارتباطه بفاتورة
  if (S.invoices.some(i => i.journalId === id)) {
    showToast('⚠ القيد مرتبط بفاتورة، احذف الفاتورة أولاً', 'error');
    return;
  }

  S.journalEntries = S.journalEntries.filter(e => e.id !== id);
  save();
  updateAll();
  showToast('تم الحذف', 'success');
}

/* ============================================================
   عرض جدول القيود (Render)
   ============================================================ */
function renderJournal() {
  const tbody = document.getElementById('journal-body');

  if (!S.journalEntries.length) {
    tbody.innerHTML = '<tr><td colspan="8"><div class="empty-state"><div class="empty-icon">📝</div><p>أضف أول قيد</p></div></td></tr>';
    return;
  }

  tbody.innerHTML = [...S.journalEntries].reverse().map((e, i) => `
    <tr>
      <td class="text-muted">${S.journalEntries.length - i}</td>
      <td>${e.date}</td>
      <td class="fw-800 text-accent">${e.number}</td>
      <td>${escH(e.desc)}</td>
      <td class="text-green">${fmt(e.debitTotal)}</td>
      <td class="text-red">${fmt(e.creditTotal)}</td>
      <td><span class="badge ${e.autoGenerated ? 'badge-yellow' : 'badge-green'}">${e.status || 'مرحّل'}</span></td>
      <td class="no-print"><div class="td-actions">
        <button class="btn btn-ghost btn-sm" onclick="openJournalModal('${e.id}')">✏️</button>
        <button class="btn btn-danger btn-sm" onclick="deleteJournalEntry('${e.id}')">🗑</button>
      </div></td>
    </tr>`).join('');
}
